server {
    listen 80 default_server;
    server_name _;
    root /home/darley/trueconnect/trusteme-front/dist;
    index index.html;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME /home/darley/trueconnect/trustme-back/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;
        include fastcgi_params;
        fastcgi_read_timeout 300;
    }

    location /storage {
        alias /home/darley/trueconnect/trustme-back/public/storage;
    }

    location ~ /\.ht {
        deny all;
    }
}
