<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiteSettingsSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['id' => 1, 'key' => 'site_name', 'value' => 'TrueConnect', 'type' => 'text', 'group' => 'general', 'created_at' => '2025-09-03 23:10:27', 'updated_at' => '2026-01-13 22:56:30'],
            ['id' => 2, 'key' => 'site_slogan', 'value' => 'Conexões Reais, Contratos Seguros e Proteção Total', 'type' => 'text', 'group' => 'general', 'created_at' => '2025-09-03 23:10:27', 'updated_at' => '2026-02-08 12:55:05'],
            ['id' => 3, 'key' => 'site_description', 'value' => 'Escolher o TrueConnect significa priorizar a verdade em um mundo digital repleto de incertezas. Diferente de outras certificações, nós não apenas validamos dados básicos; nós auditamos evidências reais para garantir que você tenha total segurança ao estabelecer contratos, sejam eles profissionais ou afetivos.\\n\\nOs principais motivos para nos escolher são:\\n\\nPrevenção Ativa contra Golpes: Nossa metodologia de classificação de selos é desenhada para identificar inconsistências e barrar perfis falsos ou mal-intencionados antes que eles causem danos financeiros ou emocionais.\\n\\nSegurança em Relações Afetivas: Somos pioneiros em oferecer um ambiente onde a formalização de uma relação é baseada na transparência. Você tem a certeza de quem está do outro lado, protegendo seu patrimônio e sua integridade.\\n\\nCertificação por Evidências: Nossos selos digitais não são automáticos. Eles são o resultado de uma análise criteriosa de documentos e provas enviadas, o que confere um valor de mercado e uma autoridade superior à sua presença digital.\\n\\nAcordos Transparentes e Jurídicos: Ao unir a verificação de identidade com a capacidade de gerar contratos seguros, eliminamos as \"letras miúdas\" e os desacordos futuros, garantindo que o que foi combinado entre as partes tenha lastro na verdade.', 'type' => 'textarea', 'group' => 'general', 'created_at' => '2025-09-03 23:10:27', 'updated_at' => '2026-02-08 13:18:34'],
            ['id' => 4, 'key' => 'home.hero_title', 'value' => 'Conexões Reais, Contratos Seguros e Proteção Total', 'type' => 'text', 'group' => 'home', 'created_at' => '2025-09-03 23:10:27', 'updated_at' => '2026-02-08 13:18:34'],
            ['id' => 5, 'key' => 'home.hero_subtitle', 'value' => 'Estabeleça relações afetivas e profissionais com a certeza de quem está do outro lado. Use nossos selos de veracidade baseados em evidências para prevenir golpes e garantir acordos transparentes.', 'type' => 'textarea', 'group' => 'home', 'created_at' => '2025-09-03 23:10:27', 'updated_at' => '2026-02-08 13:18:34'],
            ['id' => 6, 'key' => 'home.cta_primary_label', 'value' => 'Começar Agora', 'type' => 'text', 'group' => 'home', 'created_at' => '2025-09-03 23:10:27', 'updated_at' => '2026-02-08 13:18:34'],
            ['id' => 7, 'key' => 'home.cta_secondary_label', 'value' => 'Ver Planos', 'type' => 'text', 'group' => 'home', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2026-02-08 13:18:34'],
            ['id' => 8, 'key' => 'home.cta_block_title', 'value' => 'Pronto para Começar?', 'type' => 'text', 'group' => 'home', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2026-02-08 13:18:34'],
            ['id' => 9, 'key' => 'home.cta_block_subtitle', 'value' => 'Junte-se a milhares de pessoas que já confiam no TrueConnect', 'type' => 'textarea', 'group' => 'home', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2026-02-08 13:18:34'],
            ['id' => 10, 'key' => 'about.hero_title', 'value' => 'Sobre o TrueConnect', 'type' => 'text', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 11, 'key' => 'about.hero_subtitle', 'value' => 'Somos uma empresa dedicada a transformar a forma como as equipes colaboram e gerenciam seus projetos, oferecendo soluções inovadoras e confiáveis.', 'type' => 'textarea', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 12, 'key' => 'about.mission_title', 'value' => 'Nossa Missão', 'type' => 'text', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 13, 'key' => 'about.mission_text', 'value' => 'Capacitar empresas de todos os tamanhos com ferramentas intuitivas e poderosas que simplificam a gestão de projetos e potencializam a colaboração em equipe.', 'type' => 'textarea', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 14, 'key' => 'about.mission_text_2', 'value' => 'Acreditamos que a tecnologia deve ser um facilitador, não um obstáculo. Por isso, desenvolvemos soluções que são ao mesmo tempo sofisticadas e fáceis de usar.', 'type' => 'textarea', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 15, 'key' => 'about.values_title', 'value' => 'Nossos Valores', 'type' => 'text', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 16, 'key' => 'about.team_title', 'value' => 'Nossa Equipe', 'type' => 'text', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 17, 'key' => 'about.team_subtitle', 'value' => 'Profissionais apaixonados por tecnologia e dedicados a criar as melhores soluções para nossos clientes.', 'type' => 'textarea', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 18, 'key' => 'about.history_title', 'value' => 'Nossa História', 'type' => 'text', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 19, 'key' => 'about.cta_title', 'value' => 'Faça parte da nossa história', 'type' => 'text', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 20, 'key' => 'about.cta_subtitle', 'value' => 'Junte-se a milhares de empresas que já confiam no TrueConnect para gerenciar seus projetos e alcançar seus objetivos.', 'type' => 'textarea', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 21, 'key' => 'about.cta_button', 'value' => 'Começar Agora', 'type' => 'text', 'group' => 'about', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 22, 'key' => 'contact_email', 'value' => 'contato@TrueConnect.com', 'type' => 'text', 'group' => 'contact', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 23, 'key' => 'contact_phone', 'value' => '(11) 99999-9999', 'type' => 'text', 'group' => 'contact', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 24, 'key' => 'contact_address', 'value' => 'Rua das Pedras, 128 - Bairro das canárias -  São João', 'type' => 'textarea', 'group' => 'contact', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2026-02-08 01:55:21'],
            ['id' => 25, 'key' => 'mercado_pago_enabled', 'value' => '1', 'type' => 'boolean', 'group' => 'payment', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 26, 'key' => 'mercado_pago_public_key', 'value' => '', 'type' => 'text', 'group' => 'payment', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 27, 'key' => 'mercado_pago_access_token', 'value' => '', 'type' => 'text', 'group' => 'payment', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 28, 'key' => 'email_notifications_enabled', 'value' => '1', 'type' => 'boolean', 'group' => 'email', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 29, 'key' => 'welcome_email_enabled', 'value' => '1', 'type' => 'boolean', 'group' => 'email', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 30, 'key' => 'meta_keywords', 'value' => 'certificação digital, contratos digitais, selo de confiança, segurança digital', 'type' => 'textarea', 'group' => 'seo', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 31, 'key' => 'meta_description', 'value' => 'TrueConnect oferece certificação digital e contratos seguros para empresas. Aumente a confiança dos seus clientes com nossos selos digitais.', 'type' => 'textarea', 'group' => 'seo', 'created_at' => '2025-09-03 23:10:28', 'updated_at' => '2025-09-03 23:10:28'],
            ['id' => 32, 'key' => 'contact_email_primary', 'value' => 'oi@TrueConnect.com', 'type' => 'text', 'group' => 'contact', 'created_at' => '2025-09-03 23:58:48', 'updated_at' => '2026-02-08 01:55:14'],
            ['id' => 33, 'key' => 'contact_email_support', 'value' => 'financeiro@TrueConnect.com', 'type' => 'text', 'group' => 'contact', 'created_at' => '2025-09-03 23:58:48', 'updated_at' => '2026-02-08 01:55:14'],
            ['id' => 34, 'key' => 'contact_phone_primary', 'value' => '3198555555', 'type' => 'text', 'group' => 'contact', 'created_at' => '2025-09-03 23:58:48', 'updated_at' => '2025-09-04 01:00:51'],
            ['id' => 35, 'key' => 'contact_phone_secondary', 'value' => '111111111111', 'type' => 'text', 'group' => 'contact', 'created_at' => '2025-09-03 23:58:48', 'updated_at' => '2025-09-04 00:14:35'],
            ['id' => 36, 'key' => 'contact_hours', 'value' => '', 'type' => 'textarea', 'group' => 'contact', 'created_at' => '2025-09-03 23:58:48', 'updated_at' => '2025-09-04 00:13:34'],
            ['id' => 37, 'key' => 'home.features', 'value' => '[{\"title\":\"Selos de Veracidade por Evidências\",\"text\":\"Certificação baseada na análise rigorosa de documentos e provas enviadas, garantindo que as informações declaradas sejam legítimas e classificadas por nível de confiança.\"},{\"title\":\"Contratos Afetivos e Profissionais\",\"text\":\"Formalize relações e acordos com validade jurídica, utilizando nossa base de dados verificada para prevenir golpes, fraudes e evitar desacordos futuros entre as partes.\"},{\"title\":\"Proteção e Antifraude\",\"text\":\"Camada de segurança especializada na identificação de inconsistências documentais, oferecendo um ambiente blindado para quem busca conexões reais e seguras.\"}]', 'type' => 'json', 'group' => 'home', 'created_at' => '2026-02-08 12:55:06', 'updated_at' => '2026-02-08 13:23:53'],
            ['id' => 38, 'key' => 'home.stats', 'value' => '[{\"value\":\"1000+\",\"label\":\"Clientes Atendidos\"},{\"value\":\"5000+\",\"label\":\"Selos Certificados\"},{\"value\":\"99.9%\",\"label\":\"Uptime\"},{\"value\":\"24/7\",\"label\":\"Suporte\"}]', 'type' => 'json', 'group' => 'home', 'created_at' => '2026-02-08 12:55:06', 'updated_at' => '2026-02-08 13:24:37'],
            ['id' => 39, 'key' => 'home.steps', 'value' => '[{\"title\":\"Cadastro e Perfil Verificável\",\"text\":\"Crie sua conta na plataforma TrueConnect e preencha seu perfil com as informações básicas. A partir daí, você será orientado sobre quais documentos e evidências são necessários para iniciar o processo de verificação. Quanto mais completo seu perfil e suas provas, maior será o nível de confiança que você poderá alcançar.\"},{\"title\":\"Obtenção de Selos de Veracidade\",\"text\":\"Envie os documentos solicitados (RG, CPF, comprovante de residência, certidões, entre outros) diretamente pela plataforma. Nossa equipe e sistema realizam uma auditoria criteriosa das evidências apresentadas. Após a análise, você recebe um selo digital classificado que atesta publicamente o nível de veracidade das suas informações, aumentando sua credibilidade e protegendo você e seus futuros parceiros contra fraudes.\"},{\"title\":\"Criação de Contratos em Tempo Real\",\"text\":\"Com os selos validados, você pode conectar-se com outras pessoas verificadas e criar contratos personalizados diretamente na plataforma. As cláusulas são combinadas em tempo real entre as partes, permitindo ajustes, negociações e acordos transparentes antes da assinatura digital. Tudo fica registrado de forma segura e com validade jurídica, garantindo que ambos os lados cumpram o que foi acordado.\"}]', 'type' => 'json', 'group' => 'home', 'created_at' => '2026-02-08 12:55:06', 'updated_at' => '2026-02-08 13:27:31']
        ];

        foreach ($data as $row) {
            DB::table('site_settings')->insert($row);
        }
    }
}
